### ISSUE TITLE
Expected hydro data format ?

### ISSUE THREAD

**Issue by simonweppe** [serjaaa/lagrangian-betweenness#2]
Hi there @serjaaa and thanks a lot for sharing your code ! Great approach to look at connectivity. 

In the instructions, it is mentioned 
_1 - Change line 51 and 52 in betw_computation.cpp with the actual path to the folder named "Outputs", which is found inside code_Betweenness folder_

I couldnt find the **code_Betweenness** folder, I suppose it's not included for space reason. Would it be the files mentioned in your paper ? e.g. GLOBAL_REANALYSIS_PHY_001_030 provided by E.U. Copernicus Marine Service

Really keen to try to test this on our study site (NZ).

Regards,
Simon

**Comment by serjaaa** [comment]
Hi Simon,
Thanks a lot for your message and interest :))
Indeed, you are totally right, the instructions are not clear at all! In
line 51 you simply have the path of the input files (as you said, the
velocity fields used for the integration of the trajectories). That path
can be changed thus depending on where you have those files in your
computer basically. Sorry for that!
Cheers from Italy!
enrico

Il giorno mar 24 ago 2021 alle ore 10:16 simonweppe <
***@***.***> ha scritto:

**Comment by simonweppe** [comment]
Thanks - I'll give it a go !
